config/routes.rb
Rails.application.routes.draw do
  get 'bienvenido/index'
  resources :articulos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def new
    @articulo = Articulo.new
  end

  def create
    @articulo = Articulo.new(params.require(:articulo).permit(:title, :text))
    # retorna un boolean indicando si fue creado o no.
    @articulo.save
    redirect_to @article
  end

  def show
    @articulo = Articulo.find(params[:id])
  end

  def index
    @articulos = Articulo.all
  end

  def create
    @articulo = Articulo.new(articulo_params)
    if @articulo.save
        redirect_to @articulo
    else
      render 'new'
    end
  #  render plain: params[:articulo].inspect
  end

  def edit
    @articulo = Articulo.find(params[:id])
  end

  def update
    @articulo = Articulo.find(params[:id])
    if @articulo.update(articulo_params)
      redirect_to @articulo
    else
      render 'edit'
    end
  end

  private
    def articulo_params
      params.require(:articulo).permit(:title, :text)
    end
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/views/articulos/_form.html.erb
<%= form_with model: @articulo, local: true do |form| %>

  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@aticulo.errors.count, "error") %> pohibido
        Este artículo contiene:
      </h2>
      <ul>
        <% @articulo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <% end %>

app/views/articulos/edit.html.erb
<h1>Edición Artículo</h1>

<%= form_with(model: @articulo, local: true) do |form| %>

  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@articulo.errors.count, "error") %> prohibido
        Este artículo contiene:
      </h2>
      <ul>
        <% @articulo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Regresar', articulos_path %>

app/views/articulos/index.html.erb
<h1>Lista de articulos</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Texto</th>
    <th></th>
  </tr>

  <% @articulos.each do |articulo| %>
  <tr>
    <td><%= articulo.title %></td>
    <td><%= articulo.text %></td>
    <td><%= link_to 'Show', articulo_path(articulo) %></td>
    <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Crear', :action=>'new', controller: 'articulos' %>
<%= link_to 'Regresar', controller: 'bienvenido' %>

app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>
<!--Para crear un formulario dentro de esta plantilla, usará un generador de formularios.
Generador de formularios primario para Rails se proporciona mediante un método auxiliar llamado form_with.-->
<%= render 'form' %>

<%= link_to 'Regresar', articulos_path %>



<!--<%= link_to 'Regresar', :action=>'index', controller: 'articulos' %>-->

app/views/articulos/show.html.erb
<p>
  <strong>title:</strong>
  <%= @articulo.title %>
</p>

<p>
  <strong>title:</strong>
  <%= @articulo.text %>
</p>
<%= link_to 'Editar', edit_articulo_path(@articulo) %>
<%= link_to 'Regresar', :action=>'new', controller: 'articulos' %>

app/views/bienvenido/index.html.erb
<h1>Bienvenido#index</h1>
<p>Find me in app/views/bienvenido/index.html.erb</p>
<h1>Hola !!</h1>
<p>Hola Rails!!</p>
<%= link_to 'Mi blog', controller: 'articulos' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>